// try{
  console.log('try')
  throw new Error('Error')
  console.log("oops!")
// }catch(err){
//   console.log("An error occurred but no effect",err)
// }
console.log('done')